import NpcSummaryDefinitionStatics.method1166
import Gl2dTextureStatics.method241
import SizeBoundedSoftCacheStatics.method1343
import TextureGeneratorStatics.method1397
import FrameBufferObjectStatics.method1501
import BinaryGraphicsOptionStateStatics.method1767
import LightDetailOptionStateStatics.method1802
import ConfigFlagUtilStatics.method1916
import NpcDefinitionCacheStatics.method1987
import CompassSmootherStatics.method2017
import SocketFactoryStatics.method2049
import MaterialPassStatics.method2138
import WaterMaterialPassStatics.method2148
import SkyboxGradient.method2334
import SceneObjectEntityStatics.method2405
import FontStatics.method2570
import SkeletalAnimFrameLoaderStatics.method349
import DragDropControllerStatics.method2708
import HslAdjustTextureNodeStatics.method3127
import ClampTextureNodeStatics.method3150
import WidgetTextConfigStatics.method362
import SolidFillComponentStatics.method198
import GameClock.method599
import Direct3dModelStatics.method661
import ChatCommandProcessor.method705
import java.io.File
import java.io.IOException
import java.util.*

class ClientGameLoopNode internal constructor(var anInt6872: Int, var anInt6875: Int) : LinkedListNode() {
}
